version: '3.8'

services:

  postgres:
    container_name: psql_todo
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=todo_app
    ports:
      - "5432:5432"
    expose:
      - "5432"